export const images = {
  placeholder: require('./react.jpg'),
  BeeEnglish: require('./BeeEnglish.png'),
  BeeHello: require('./BeeHello.png'),
  Flower: require('./Flower.png'),
  Flower2: require('./Flower2.png'),
  FamilyExample: require('./FamilyExample.png'),
  TaskFlag: require('./TaskFlag.png'),
  BeeGraduated: require('./BeeGraduated.png'),
  BeeDiscovery: require('./BeeDiscovery.png'),
  BeeTeacher: require('./BeeTeacher.png'),
  BeeWithPencil: require('./BeeWithPencil.png'),
  BG_Detail: require('./bg_detailword.png'),
  BeeReading: require('./BeeReading.png'),
  BeePencil: require('./BeePencil.png'),
  BGDetailLesson: require('./BGDetailLesson.png'),
  MultipleChoice: require('./MultipleChoice.png'),
  OrangeLightFrame: require('./OrangeLightFrame.png'),
  OrangePrimaryFrame: require('./OrangePrimaryFrame.png'),
  Vocabulary: require('./Vocabulary.png'),
  StreakBox: require('./StreakBox.png'),
  ChestBox: require('./ChestBox.png'),
  Light: require('./Light.png'),
  ProfileBackground: require('./BackgroundProfile.png'),
  AccountBee: require('./AccountProfileBee.jpeg'),
  BeeWithHoney: require('./BeeWithHoney.png'),
  QuestionBubble: require('./QuestionBubble.png'),
}
