export const post: string =
  'Le Monde met with rabbi Delphine Derailleur in her Paris synagogue after she celebrated two bar mitzvahs in a seemingly joyful atmosphere. "I didn\'t want to steal such an important moment in these teenagers\' lives. A bar mitzvah is a celebratory occasion, not a day for the dead," said Horvilleur, a leading figure in liberal Judaism in France. However, in the audience, tearful faces hinted at the dramatic context, a few days after Hamas\' deadly attack in Israel. In the face of tragedy, the rabbi called for us not to succumb "to an absolute dehumanization of the other side."'
export const posts: PostResponse[] = [
    {
        id: 1,
        english: "Two co-defendants of former President Donald Trump remain on track to begin trial Monday after a judge rejected a series of arguments for tossing out the Georgia election interference case against them.",
        vietnamese: post,
        creator: "admin",
        level: "Beginner",
        title: "Luyện kỹ năng đọc hiểu",
        attachment: "https://www.usatoday.com/gcdn/authoring/authoring-images/2023/09/06/USAT/70779211007-xxx-motions-ba-040-4181316.JPG",
        flag: false,
        note: "Luyện kỹ năng đọc hiểu",
        type: "Beginner",
        topic: "Beginner",
    },
    {
        id: 2,
        english: "Sidney Powell and Kenneth Chesebro, who are among the 19 individuals charged in the case, said the charges they face should be nixed on multiple grounds, including the fact that prosecutors have targeted an overly-broad range of conduct. The sweeping indictment states that various alleged acts by different defendants -- from urging legislators to reject lawful electoral votes to stealing voting equipment software -- were part of a criminal conspiracy to unlawfully change the outcome of the 2020 presidential election.",
        vietnamese: post,
        creator: "admin",
        level: "Beginner",
        title: "Luyện kỹ năng đọc hiểu",
        attachment: "https://www.usatoday.com/gcdn/authoring/authoring-images/2023/09/06/USAT/70779211007-xxx-motions-ba-040-4181316.JPG",
        flag: false,
        note: "Luyện kỹ năng đọc hiểu",
        type: "Beginner",
        topic: "Beginner",
    },
    {
        id: 3,
        english: "The indictment also charges that the defendants conspired to commit fraud, which is a crime. The indictment also charges that the defendants conspired to commit fraud, which is a crime.",
        vietnamese: post,
        creator: "admin",
        level: "Beginner",
        title: "Luyện kỹ năng đọc hiểu",
        attachment: "https://www.usatoday.com/gcdn/authoring/authoring-images/2023/09/06/USAT/70779211007-xxx-motions-ba-040-4181316.JPG",
        flag: false,
        note: "Luyện kỹ năng đọc hiểu",
        type: "Beginner",
        topic: "Beginner",
    },
    {
        id: 4,
        english: "Fulton County Superior Court Judge Scott McAfee said in a Wednesday order that Georgia prosecutors are allowed to bring criminal prosecutions related to elections, even though the federal Electoral Count Act governs Congress’ process for counting electoral votes. On Tuesday, McAfee also rejected several other pre-trial arguments from Powell and Cheeseboard.",
        vietnamese: post,
        creator: "admin",
        level: "Beginner",
        title: "Luyện kỹ năng đọc hiểu",
        attachment: "https://www.usatoday.com/gcdn/authoring/authoring-images/2023/09/06/USAT/70779211007-xxx-motions-ba-040-4181316.JPG",
        flag: false,
        note: "Luyện kỹ năng đọc hiểu",
        type: "Beginner",
        topic: "Beginner",
    }
]
