export const AUTH_ROUTE = {
  BOTTOM_TAB: {
    HOME_SCREEN: 'HOME_SCREEN',
    LEARNING_SCREEN: 'LEARNING_SCREEN',
    GAME_SCREEN: 'GAME_SCREEN',
    PROFILE_SCREEN: 'PROFILE_SCREEN',
  },

  SPLASH_SCREEN: 'SPLASH_SCREEN',
}

export const PUBLIC_ROUTE = {}
